/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Applic_News;

/**
 *
 * @author Ophiran
 */
public class Applic_News extends javax.swing.JFrame {

    /**
     * Creates new form Applic_News
     */
    public Applic_News() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Connect_button = new javax.swing.JButton();
        Deconnect_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ville_label = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        journaliste_tBox = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        texte_tBox = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        politique_rButton = new javax.swing.JRadioButton();
        inter_rButton = new javax.swing.JRadioButton();
        sport_rButton = new javax.swing.JRadioButton();
        people_rButton = new javax.swing.JRadioButton();
        important_cBox = new javax.swing.JCheckBox();
        enreg_button = new javax.swing.JButton();
        env_button = new javax.swing.JButton();
        annuler_button = new javax.swing.JButton();
        news_scrollPane = new javax.swing.JScrollPane();
        news_table = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        evenement_textArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Connect_button.setText("Se connecter");
        getContentPane().add(Connect_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 55, -1, -1));

        Deconnect_button.setText("Se deconnecter");
        getContentPane().add(Deconnect_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 55, 125, -1));

        jLabel1.setText("Nombre de news envoyees durant cette session:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 240, -1));

        ville_label.setText("jLabel2");
        getContentPane().add(ville_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 59, 58, -1));

        jLabel3.setText("Journaliste:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        journaliste_tBox.setText("jTextField1");
        getContentPane().add(journaliste_tBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 126, 160, -1));

        jLabel4.setText("Texte:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 167, -1, -1));

        texte_tBox.setText("jTextField2");
        getContentPane().add(texte_tBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 164, 250, -1));

        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 60, -1, -1));

        politique_rButton.setText("Politique");
        getContentPane().add(politique_rButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        inter_rButton.setText("International");
        getContentPane().add(inter_rButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        sport_rButton.setText("Sports");
        getContentPane().add(sport_rButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        people_rButton.setText("People et ragots");
        getContentPane().add(people_rButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        important_cBox.setText("Important");
        getContentPane().add(important_cBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 93, -1));

        enreg_button.setText("Enregistrer");
        getContentPane().add(enreg_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 148, -1));

        env_button.setText("Envoyer");
        getContentPane().add(env_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 148, -1));

        annuler_button.setText("Annuler");
        getContentPane().add(annuler_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 150, -1));

        news_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        news_scrollPane.setViewportView(news_table);

        getContentPane().add(news_scrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 360, 100));

        jLabel6.setText("Log des evenements:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, -1, -1));

        evenement_textArea.setColumns(20);
        evenement_textArea.setRows(5);
        jScrollPane2.setViewportView(evenement_textArea);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 360, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Applic_News.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Applic_News.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Applic_News.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Applic_News.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Applic_News().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Connect_button;
    private javax.swing.JButton Deconnect_button;
    private javax.swing.JButton annuler_button;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton enreg_button;
    private javax.swing.JButton env_button;
    private javax.swing.JTextArea evenement_textArea;
    private javax.swing.JCheckBox important_cBox;
    private javax.swing.JRadioButton inter_rButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField journaliste_tBox;
    private javax.swing.JScrollPane news_scrollPane;
    private javax.swing.JTable news_table;
    private javax.swing.JRadioButton people_rButton;
    private javax.swing.JRadioButton politique_rButton;
    private javax.swing.JRadioButton sport_rButton;
    private javax.swing.JTextField texte_tBox;
    private javax.swing.JLabel ville_label;
    // End of variables declaration//GEN-END:variables
}
