/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Applic_Salle;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeModel;
import libNews.DialInfoNews;
import libNews.News;

/**
 *
 * @author ekym
 */
public class DialRechCleNews extends javax.swing.JDialog implements ActionListener, TreeSelectionListener {
    private java.awt.Frame parent;
    
    /**
     * Creates new form DialRechClefNews
     * @param parent 
     * @param modal 
     * @param listeSport
     * @param listePol 
     * @param listeInter  
     */
    public DialRechCleNews(java.awt.Frame parent, boolean modal, DefaultListModel listePol, DefaultListModel listeSport, DefaultListModel listeInter) {
        super(parent, modal);
        initComponents();
        
        this.parent = parent;
        quitter_button.addActionListener(this);
        details_button.addActionListener(this);
        JTree.addTreeSelectionListener(this);
        
        Vector<String> listKeywords;
        Vector<News> listNews = new Vector<News>();
        
        for(int i = 0; i < listePol.size(); i++){
            listNews.addElement((News)listePol.elementAt(i));
        }
        for(int i = 0; i < listeSport.size(); i++){
            listNews.addElement((News)listeSport.elementAt(i));
        }
        for(int i = 0; i < listeInter.size(); i++){
            listNews.addElement((News)listeInter.elementAt(i));
        }
        listKeywords = CreateListKeywords(listNews);
        DefaultMutableTreeNode treeRoot = ConstructTree(listNews, listKeywords);
        JTree.setModel(new DefaultTreeModel(treeRoot));
        
    }
    
    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource().equals(quitter_button)){
            this.dispose();
        }
        if(e.getSource().equals(details_button)){
            try{
                DefaultMutableTreeNode treeNode = (DefaultMutableTreeNode)JTree.getLastSelectedPathComponent();
                DialInfoNews dial = new DialInfoNews(parent, rootPaneCheckingEnabled, (News)treeNode.getUserObject());
                dial.setVisible(true);
            }
            catch(NullPointerException npe){
                
            }
        }
    }
    
    @Override
    public void valueChanged(TreeSelectionEvent e) {
        try{
            DefaultMutableTreeNode treeNode = (DefaultMutableTreeNode)JTree.getLastSelectedPathComponent();
            DialInfoNews dial = new DialInfoNews(parent, rootPaneCheckingEnabled, (News)treeNode.getUserObject());
            dial.setVisible(true);
        }
        catch(NullPointerException npe){

        }
    }
    private Vector<String> CreateListKeywords(Vector<News> listNews){
        Vector<String> listKeywords = new Vector<String>();
        String[] bufferKeywords = new String[20];
        for(News n : listNews){
            bufferKeywords = n.getListeMotsCles();
            for(String s : bufferKeywords){
                if(!listKeywords.contains(s))
                    listKeywords.add(s);
            }
        }
        
        return listKeywords;
    }
    
    private DefaultMutableTreeNode ConstructTree(Vector<News> listNews, Vector<String> listKeywords){
        DefaultMutableTreeNode root = new DefaultMutableTreeNode("Mots cles");
        
        for(String s : listKeywords){
            DefaultMutableTreeNode keynode = new DefaultMutableTreeNode(s);
            root.add(keynode);
            for(News n : listNews){
                if(n.containsMotCle(s))
                    keynode.add(new DefaultMutableTreeNode(n));
            }
        }
        
        return root;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JTree = new javax.swing.JTree();
        quitter_button = new javax.swing.JButton();
        details_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setViewportView(JTree);

        quitter_button.setText("Quitter");

        details_button.setText("Details");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(quitter_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(details_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(details_button)
                        .addGap(18, 18, 18)
                        .addComponent(quitter_button)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree JTree;
    private javax.swing.JButton details_button;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton quitter_button;
    // End of variables declaration//GEN-END:variables

}
