/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Applic_Salle;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import libNews.DialInfoNews;
import libNews.News;

/**
 *
 * @author ekym
 */
public class DialRechCatNews extends javax.swing.JDialog implements ActionListener {

    private DefaultListModel listeSelec, listePol, listeSport, listeInter;
    News[] arr;
    java.awt.Frame parent;
    /**
     * Creates new form DialRechCatNews
     * @param parent
     * @param modal 
     * @param listePol 
     * @param listeSport 
     * @param listeInter  
     */
    public DialRechCatNews(java.awt.Frame parent, boolean modal, DefaultListModel listePol, DefaultListModel listeSport, DefaultListModel listeInter) {
        super(parent, modal);
        initComponents();
        radioGroup.add(pol_radio);
        radioGroup.add(sport_radio);
        radioGroup.add(inter_radio);
        details_button.addActionListener(this);
        quitter_button.addActionListener(this);
        sort_button.addActionListener(this);
        table.addMouseListener(new MouseAdapter(){
                                    @Override
                                    public void mouseClicked(MouseEvent e)
                                    {   
                                        getDetails(e);
                                    }
                                });
        this.listePol = listePol;
        this.listeSport = listeSport;
        this.listeInter = listeInter;
        this.parent = parent;
        
        
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource().equals(quitter_button)){
            this.dispose();
        }
        if(e.getSource().equals(sort_button)){
            listeSelec = listePol;
            if(pol_radio.isSelected()){
                listeSelec = listePol;
            }
            if(sport_radio.isSelected()){
                listeSelec = listeSport;
            }
            if(inter_radio.isSelected()){
                listeSelec = listeInter;
            }
            arr = new News[listeSelec.getSize()];
            listeSelec.copyInto(arr);
            Object[][] data = new Object[arr.length][4];
            for(int i = 0 ; i < arr.length ; i++){
                data[i][0] = arr[i].getContenu().toString();
                data[i][1] = arr[i].getType().toString();
                if(arr[i].getImportance() == true)
                    data[i][2] = "OUI";
                else
                    data[i][2] = "NON";
                data[i][3] = arr[i].getAuteur().getLogin().toString();
            }
            String[] colNames = { "News", "Type", "Important", "Auteur"};
            DefaultTableModel model = new DefaultTableModel(data, colNames);
            table.setModel(model);
        }
        if(e.getSource().equals(details_button)){
            try{
                DialInfoNews dial = new DialInfoNews(parent, rootPaneCheckingEnabled, arr[table.getSelectedRow()]);
                dial.setVisible(true);
            }
            catch(NullPointerException npe){
                
            }
        }
    }
    
    /**
     *
     * @param e
     */
    public void getDetails(MouseEvent e) {
        try{
            DialInfoNews dial = new DialInfoNews(parent, rootPaneCheckingEnabled, arr[table.rowAtPoint(e.getPoint())]);
            dial.setVisible(true);
        }
        catch(NullPointerException npe){

        }
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioGroup = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        details_button = new javax.swing.JButton();
        quitter_button = new javax.swing.JButton();
        pol_radio = new javax.swing.JRadioButton();
        sport_radio = new javax.swing.JRadioButton();
        inter_radio = new javax.swing.JRadioButton();
        sort_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        details_button.setText("Details");

        quitter_button.setText("Quitter");

        pol_radio.setText("Politique");

        sport_radio.setText("Sport");

        inter_radio.setText("International");

        sort_button.setText("Trier");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(quitter_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(details_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sort_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sport_radio)
                            .addComponent(pol_radio)
                            .addComponent(inter_radio))
                        .addContainerGap(26, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(quitter_button)
                        .addGap(26, 26, 26)
                        .addComponent(details_button)
                        .addGap(18, 18, 18)
                        .addComponent(sort_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pol_radio)
                        .addGap(18, 18, 18)
                        .addComponent(sport_radio)
                        .addGap(18, 18, 18)
                        .addComponent(inter_radio)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton details_button;
    private javax.swing.JRadioButton inter_radio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton pol_radio;
    private javax.swing.JButton quitter_button;
    private javax.swing.ButtonGroup radioGroup;
    private javax.swing.JButton sort_button;
    private javax.swing.JRadioButton sport_radio;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables




}
