/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Applic_Salle;

import Applic_Salle.Journaliste;
import constantes.Categories;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import libNews.News;

/**
 *
 * @author ekimd_000
 */
public class DialTraitement extends javax.swing.JDialog implements ActionListener{

    /**
     * Creates new form DialTraitement
     */
    public News newsEdited;
    public boolean isValidate;
    private Journaliste journalisteConnecte;
    public DialTraitement(java.awt.Frame parent, boolean modal, News news, Journaliste auteur) {
        super(parent, modal);
        initComponents();
        radioGroup.add(radioPolitique);
        radioGroup.add(radioInternationale);
        radioGroup.add(radioSport);
        radioGroup.add(radioPeople);
        validerButton.addActionListener(this);
        annulerButton.addActionListener(this);
        
        if(news != null) {
            newsEdited = news;
            textFieldContenu.setText(newsEdited.getContenu());
            textArea.setText(newsEdited.getCommentaires());
            checkBox.setSelected(newsEdited.getImportance());
            keyWords.setText(newsEdited.getMotsCles());
            if(newsEdited.getType().equals(Categories.Internationale))
                radioGroup.setSelected(radioInternationale.getModel(), modal);
            if(newsEdited.getType().equals(Categories.Politique))
                radioGroup.setSelected(radioPolitique.getModel(), modal);  
            if(newsEdited.getType().equals(Categories.Sport))
                radioGroup.setSelected(radioSport.getModel(), modal);
            if(newsEdited.getType().equals(Categories.People))
                radioGroup.setSelected(radioPeople.getModel(), modal);
        }   
        else{
            System.out.println("ERROR: no news referenced");//TODO
            this.dispose();
        }
        if(auteur != null) {
            journalisteConnecte = auteur;
        }
        else{
            System.out.println("ERROR: no journalist referenced");//TODO
            this.dispose();
        }
    }
            
    
    @Override
    public void actionPerformed(ActionEvent ae) {
        if(ae.getSource().equals(validerButton)){
            newsEdited.setContenu(textFieldContenu.getText());
            newsEdited.setImportance(checkBox.isSelected());
            newsEdited.setMotsCles(keyWords.getText());
            newsEdited.setAuteur(journalisteConnecte);
            newsEdited.setCommentaires(textArea.getText());
            if(radioInternationale.isSelected()){
                newsEdited.setType(Categories.Internationale);
            }
            if(radioPolitique.isSelected()){
                newsEdited.setType(Categories.Politique);
            }
            if(radioSport.isSelected()){
                newsEdited.setType(Categories.Sport);
            }
            if(radioPeople.isSelected()){
                newsEdited.setType(Categories.People);
            }
            
            isValidate = true;
            this.dispose();
                    
        }
        if(ae.getSource().equals(annulerButton)){
            isValidate = false;
            this.dispose();
        }
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioGroup = new javax.swing.ButtonGroup();
        radioPolitique = new javax.swing.JRadioButton();
        radioInternationale = new javax.swing.JRadioButton();
        radioSport = new javax.swing.JRadioButton();
        radioPeople = new javax.swing.JRadioButton();
        checkBox = new javax.swing.JCheckBox();
        validerButton = new javax.swing.JButton();
        annulerButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        keyWords = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        textFieldContenu = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        radioPolitique.setText("Politique");

        radioInternationale.setText("Internationale");

        radioSport.setText("Sport");

        radioPeople.setText("People");

        checkBox.setText("Important");

        validerButton.setText("Valider");

        annulerButton.setText("Annuler");

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        jLabel1.setText("Texte :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(validerButton)
                .addGap(101, 101, 101)
                .addComponent(annulerButton)
                .addGap(0, 222, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(keyWords)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(textFieldContenu, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radioPeople)
                                    .addComponent(radioSport)
                                    .addComponent(radioInternationale)
                                    .addComponent(radioPolitique, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(checkBox))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textFieldContenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(checkBox)
                        .addGap(18, 18, 18)
                        .addComponent(radioPolitique)
                        .addGap(18, 18, 18)
                        .addComponent(radioInternationale)
                        .addGap(18, 18, 18)
                        .addComponent(radioSport)
                        .addGap(18, 18, 18)
                        .addComponent(radioPeople)))
                .addGap(43, 43, 43)
                .addComponent(keyWords, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(validerButton)
                    .addComponent(annulerButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annulerButton;
    private javax.swing.JCheckBox checkBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField keyWords;
    private javax.swing.ButtonGroup radioGroup;
    private javax.swing.JRadioButton radioInternationale;
    private javax.swing.JRadioButton radioPeople;
    private javax.swing.JRadioButton radioPolitique;
    private javax.swing.JRadioButton radioSport;
    private javax.swing.JTextArea textArea;
    private javax.swing.JTextField textFieldContenu;
    private javax.swing.JButton validerButton;
    // End of variables declaration//GEN-END:variables


}
