/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Applic_Salle;

import constantes.Categories;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import libNews.DialInfoNews;
import libNews.News;

/**
 *
 * @author ekym
 */
public class DialRechPeopleNews extends javax.swing.JDialog implements ActionListener {

    private Vector<News> listeNewsPeople, listeTriee;
    java.awt.Frame parent;
    /**
     * Creates new form DialRechCatNews
     */
    public DialRechPeopleNews(java.awt.Frame parent, boolean modal, Vector<News> listeNewsPeople) {
        super(parent, modal);
        initComponents();
        details_button.addActionListener(this);
        quitter_button.addActionListener(this);
        table.addMouseListener(new MouseAdapter(){
                                    @Override
                                    public void mouseClicked(MouseEvent e)
                                    {   
                                        getDetails(e);
                                    }
                                });
        this.listeNewsPeople = listeNewsPeople;
        this.parent = parent;
        
        listeTriee = new Vector<News>();
        for(News n : listeNewsPeople){
            if(n.getType().equals(Categories.People) && (Applic_Salle.journalisteConnecte.getId().equals("Administrateur") 
                    || n.getAuteur().getLogin().equals(Applic_Salle.journalisteConnecte.getLogin())))
            {
                listeTriee.add(n);
            }
        }
        
        Object[][] data = new Object[listeTriee.size()][4];
        int i = 0;
        for(News n : listeTriee){
            data[i][0] = n.getContenu().toString();
            data[i][1] = n.getType().toString();
            if(n.getImportance() == true)
                data[i][2] = "OUI";
            else
                data[i][2] = "NON";
            data[i][3] = n.getAuteur().getLogin().toString();
            i++;
        }
        String[] colNames = { "News", "Type", "Important", "Auteur"};
        DefaultTableModel model = new DefaultTableModel(data, colNames);
        table.setModel(model);
        
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource().equals(quitter_button)){
            this.dispose();
        }
        
        if(e.getSource().equals(details_button)){
            try{
                DialInfoNews dial = new DialInfoNews(parent, rootPaneCheckingEnabled, listeTriee.elementAt(table.getSelectedRow()));
                dial.setVisible(true);
            }
            catch(NullPointerException npe){
                
            }
            catch(ArrayIndexOutOfBoundsException oe) {
            	
            }
        }
    }
    
    public void getDetails(MouseEvent e) {
        try{
            DialInfoNews dial = new DialInfoNews(parent, rootPaneCheckingEnabled, listeTriee.elementAt(table.rowAtPoint(e.getPoint())));
            dial.setVisible(true);
        }
        catch(NullPointerException npe){

        }
        catch(ArrayIndexOutOfBoundsException oe) {
        	
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        quitter_button = new javax.swing.JButton();
        details_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        quitter_button.setText("Quitter");

        details_button.setText("Details");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(details_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(quitter_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(quitter_button)
                        .addGap(18, 18, 18)
                        .addComponent(details_button)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton details_button;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton quitter_button;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
